# Nombre del programa final
PROGRAMA := suma

# TODO 1: Definí el compilador a usar
#         Asigná el valor "gcc" a la variable CC
CC :=

# TODO 2: Definí las flags de compilación
#         Asigná el valor "-Wall" a la variable CFLAGS
CFLAGS :=

# Regla principal: indica qué construir al ejecutar `make`
all: $(PROGRAMA)

# Regla para generar el ejecutable a partir de suma.c
# TODO 3: Completá el comando de compilación
#         Usá las variables $(CC) y $(CFLAGS), el archivo suma.c,
#         y el flag -o $(PROGRAMA) para nombrar el ejecutable
$(PROGRAMA): suma.c
	# Escribí el comando aquí (reemplazá este comentario)

# Regla para limpiar los archivos generados
# TODO 4: Completá el comando para eliminar el ejecutable
#         Usá rm -f y la variable $(PROGRAMA)
clean:
	# Escribí el comando aquí (reemplazá este comentario)

.PHONY: all clean
